continue

diff --git a/.github/workflows/performance_test.yml b/.github/workflows/performance_test.yml
--- a/.github/workflows/performance_test.yml
+++ b/.github/workflows/performance_test.yml
@@ -2,8 +2,8 @@ name: Performance Test
 
 on:
   schedule:
-    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
-  workflow_dispatch:      # Allows manual triggering
+    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
+  workflow_dispatch: # Allows manual triggering
 
 jobs:
   performance_test:
@@ -13,53 +13,52 @@ jobs:
       OXEN_API_KEY: ${{ secrets.OXEN_API_KEY }}
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Install dependencies
-      run: brew install pkg-config ffmpeg imagemagick
+      - name: Install dependencies
+        run: brew install pkg-config ffmpeg imagemagick
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'  # Specify the Python version you need
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: "3.x" # Specify the Python version you need
 
-    - name: Cache Rust dependencies
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.cargo/bin/
-          ~/.cargo/registry/index/
-          ~/.cargo/registry/cache/
-          ~/.cargo/git/db/
-          target/
-        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+      # https://youtrack.jetbrains.com/issue/RUST-12079/Failure-to-show-stack-trace-when-running-cargo-tests
+      - name: Install LLVM Linker
+        run: |
+          brew install llvm
+          echo '[target.aarch64-apple-darwin]' >> ~/.cargo/config
+          echo 'rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld"]' >> ~/.cargo/config
 
-    # https://youtrack.jetbrains.com/issue/RUST-12079/Failure-to-show-stack-trace-when-running-cargo-tests
-    - name: Install LLVM Linker
-      run: |
-        brew install llvm
-        echo '[target.aarch64-apple-darwin]' >> ~/.cargo/config
-        echo 'rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld"]' >> ~/.cargo/config
+      - name: Cache Rust dependencies
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+            target/
+          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
 
-    - name: Install latest Rust toolchain
-      uses: actions-rs/toolchain@v1
-      with:
-        target: x86_64-apple-darwin
-        default: true
-        profile: minimal
-        toolchain: stable
-        override: true
+      - name: Install latest Rust toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          target: x86_64-apple-darwin
+          default: true
+          profile: minimal
+          toolchain: stable
+          override: true
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip || true
-        pip install -r cli-tests/requirements.txt || true
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip || true
+          pip install -r cli-tests/requirements.txt || true
 
-    - name: Build Rust project
-      run: cargo build
+      - name: Build Rust project
+        run: cargo build
 
-
-    - name: Run tests
-      run: |
-        ruby cli-test/spec/spec_remote_hub/test.rb
+      - name: Run tests
+        run: |
+          ruby cli-test/spec/spec_remote_hub/test.rb
